version: "3.9"

x-logging:
  &default-logging
    driver: "json-file"
    options:
      max-size: "50m"
      max-file: "10"

services:
  naxsi:
    container_name: nginx-naxsi
    build:
      context: ./
      dockerfile: Dockerfile
    image: nginx-naxsi:v1.22.1

    environment:
      TZ: Asia/Bangkok
    platform: "linux/amd64"
    logging: *default-logging
    # env_file:
    #   - .env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./naxsi-rules:/etc/nginx/naxsi-rules
      - ./naxsi-waf:/var/www/html/.naxsi-waf
      - ./logs:/var/log/nginx
      - ${PATH_CERTS}:${PATH_CERTS}:ro
    restart: always